# Generated by Django 5.1.1 on 2024-10-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_xone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_type',
            field=models.CharField(choices=[('website', 'Website'), ('book', 'Book'), ('article', 'Article'), ('music', 'Music'), ('video', 'Video')], default='website', max_length=255),
        ),
    ]
